### ISSUE TITLE
Inconsistency between TestRESTClient and FlaskTestClient

### ISSUE THREAD

**Issue by alexanderrichards** [ic-hep/pdm#104]
The former JSON encodes the data parameter on post/put whereas the latter does not. This shows up when using the self.__test client for service testing.

**Comment by sfayer** [comment]
Hmm, I still need to remember to have a look at the return types, so I'm not going to close this quite yet...

**Comment by sfayer** [comment]
Nah, the return type shouldn't be changed... It's a Response object in the FlaskTestClient which is exactly what is needed (so you can check parameters of the request). The RestClient returns just the raw data, which is what you want for easy production use. I think just normalising the JSON input has fixed the confusion sufficiently.
