### ISSUE TITLE
Worker should print basic details of what it's doing in the main worker log

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#112]
If it silently just runs the command and gets the output, then it'll be difficult to debug... It should print which request it's processing and roughly what it's planning on doing... (And the return code of the command? That sort of thing). At the moment it seems rather quiet:

```
$ ./bin/start_worker.py -d -o etc/system.worker.conf 
[2018-03-20 20:01:49,852]          Worker :     INFO : Daemon target starting...
[2018-03-20 20:01:50,081]          Worker :     INFO : Daemon shutting down..
$
```

**Comment by alexanderrichards** [comment]
yup, valid point. I didn't have time to add the logging as was trying to get things working. This is on my radar and I'll add some more verbosity.
