### ISSUE TITLE
Add pdmcli verb to get log file for a job

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#126]
This should be fairly simple, the only complexity if handling the "attempt number" correctly... It should default to the last attempt if the user doesn't specify a different attempt number.

**Comment by sfayer** [comment]
I think Alex's interface doesn't allow getting a specific attempt's log yet, so that will need tweaking.

**Comment by alexanderrichards** [comment]
the API get_output exists which retrieves the latest log file. Is there a use case for wanting anything other than the latest?
