### ISSUE TITLE
Move HRService helper functions into new module

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#182]
I shouldn't have to import HRService just to get the current user ID from a token in my service... It should have a HRUtils module for things like that instead.

**Comment by sfayer** [comment]
This is more critical than I initially thought:
HRService.get_token_userid is an _UNSAFE_ function (any user can fake an user ID), but it's not marked as such in the documentation, which is unacceptable.

All the token handling functions should have safe and unsafe versions for different uses.

**Comment by sfayer** [comment]
Hmm, I guess in my case, the token is checked before I get access to it, so it isn't quite as bad as I thought... There should also be a function for generating test tokens in a standard way.

**Comment by martynia** [comment]
Hi,

You confused me a little …

Both get_token_userid
and 
       get_token_key

Use the same unsafe TokenService.unpack method.

While the ‘key’ is a CS token itself and could be checked for integrity, the userid is just a number. If the token was tempered with a value error would be raised, wouldn’t it ?

It this operation logically not equivalent to getting a DN from a X509 proxy with openssl ? Everyone can get the DN, but cannot do much with it .

The id is used by TransferClient to add that user to the CS. We are not going to have this anymore, so would this method be ever used ?


Concerning #182, it is just a process of moving 2 (obsolete I think) static methods to HRUtils, isn’t it ?

  cheers, JM

**Comment by sfayer** [comment]
get_token_key can go away...
get_token_userid needs to stay (it's used to get the current user ID in the site service: Users own sites now). It should be split into a safe and unsafe version.

The difference is between getting the DN with openssl and getting the DN with openssl while checking the cert is actually valid: They both have different use cases and it needs care not to muddle them up.

It's all not too urgent for now, your time is probably better spent working on the gfal stuff.

**Comment by sfayer** [comment]
This is closed by #212.
