### ISSUE TITLE
User register function seems to have stopped working

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#194]
I think there is some kind of bug in the authentication config/code, but I can't obviously see it. I should track down what the problem is.

**Comment by martynia** [comment]
Is it with your site service? If so, this  is most likely because the user registration involves contacting the CS. I'm planning to work on it next week.
 JM 

Janusz Martyniak

**Comment by sfayer** [comment]
No, this is the old system... It's something to do with when I re-factored the auth system. I'll have a look at it at some point.

**Comment by sfayer** [comment]
This was just a misconfiguration in my test environment: I had to change the system DN to have the full hostname to test the site registration functionality, but forgot to update the system.auth file to match.
