### ISSUE TITLE
Worker error on listing job failure

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#221]
When the listing job fails (so has no Listing element in the output), the worker fails to upload any job status:
```
Traceback (most recent call last):
  File "/home/centos/pdm/src/pdm/workqueue/Worker.py", line 213, in _upload
    self.put('worker/jobs/%s/elements/%s' % (job_id, element_id), data=data)
  File "/home/centos/pdm/src/pdm/framework/RESTClient.py", line 142, in put
    return self.__do_request(uri, 'PUT', data)
  File "/home/centos/pdm/src/pdm/framework/RESTClient.py", line 127, in __do_request
    raise RESTException(resp.status_code, resp.text)
RESTException: HTTP 400: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Missing data attributes: ['listing']</p>
```

The returned JSON document is (for example):
```
{u'Reason': u'globus_ftp_control: gss_init_sec_context failed globus_gsi_callback_module: Could not verify credential globus_gsi_callback_module: Error with signing policy globus_gsi_callback_module: Error in OLD GAA code: The subject of the certificate "/O=pdmtest1.grid.hep.ph.ic.ac.uk/OU=Hosts/CN=pdmtest1.grid.hep.ph.ic.ac.uk" does not match the signing policies defined in /tmp/tmpcao_haL3/cd5cb273.signing_policy ', u'Code': 1, u'id': u'20.0'}
```

**Comment by alexanderrichards** [comment]
excellent, good spot.

**Comment by alexanderrichards** [comment]
> Do you have a preference?

@sfayer Any feelings on this before I go ahead and pick one?

**Comment by sfayer** [comment]
Nah, I don't mind... Whatever you think is best.

**Comment by alexanderrichards** [comment]
TBH, looking back at the two options I mentioned I'm not even sure I understand now :wink: basically I guess we keep things as they are and if pdm_gfal2_ls doesn't return a listing, the worker returns a blank listing thereby meeting the requirement else the WorkqueueService logic would have to change such that if the worker returns an element with return code != 0 we ignore the requirement.

The latter seems messier to me and certainly requires more code change. I'm leaning towards the former

**Comment by alexanderrichards** [comment]
ok great, I'll do that now then.
