### ISSUE TITLE
Listing command seems to be recursive

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#223]
Doing the standard list command from PDM cli appears to be recursively scanning the gridftp server, whereas it should only do one level in this case. I suspect that recursive is the default somewhere and it doesn't get set.

**Comment by alexanderrichards** [comment]
yes, presumably it's the default in @martynia  gfal2-ls script. I'll check now. You should be explicitly able to specify the depth as an option.

**Comment by alexanderrichards** [comment]
ok I've checked this now. Indeed the gfal2-ls script has full recursion as the default. You can pass the following to extra_opts of the job to override it:
```python
{'max_depth': 0}
```
It's my feeling however that single level, no recursion ought to probably be the default? What's your opinion?

**Comment by alexanderrichards** [comment]
the above PR is related to this issue but doesn't close it. It enables you to pass extra_opts like the one mentioned above via the WorkqueueClient (presumable from the CLI) where as before you could only do this using the RESTful interface. 

To close this issue we need #228 as a minimum unless you want to also make the default depth 0 on the worker side as well?

**Comment by sfayer** [comment]
Nah, I'm not worried about changing the default on the workers themselves... As long as the CLI & Web set the defaults (which they should) then everything should be fine.
