### ISSUE TITLE
removing users does not work

### ISSUE THREAD

**Issue by martynia** [ic-hep/pdm#258]
Most likely caused by a failure of removing a user from the site service. At the moment there is no token passed over from the HRService to the SiteService.
(CLI code available on _janusz_add_unregister_ branch).

**Comment by sfayer** [comment]
Well, there is no janusz_add_unregister branch and the current code just prints "Operation not implemented yet ...", so I don't know what you actually want. It would be better if you wrote the code so that I could then see the stack-trace or whatever...

**Comment by martynia** [comment]
A line next to one that prints that message is commented out. This is the action which is supposed to unregister (user sub command code)
J

**Comment by sfayer** [comment]
Fixed by PR #356
