### ISSUE TITLE
Listing directories with more than ~100 files seems to fail

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#283]
A directory with 100 files never returns a valid listing for some reason. I'll investigate this for now.

**Comment by sfayer** [comment]
I've debugged this, but I don't see any easy solution... Two problems:
1: StdOutDispatcher.handle_read shouldn't throw away ValueError without logging anything: Otherwise malformed JSON from the subprocess will be near impossible to debug. I suggest:
```
        try:
            done_element = json.load(self._fd)
        except ValueError as err:
            self._logger.warning("Malformed return from subprocess: %s", str(err))
            self.close()
            return
```
This then gets the following output log information:
``` WARNING : Malformed return from subprocess: Unterminated string starting at: line 1 column 4095 (char 4094)```

2: The handle_read is called, if a read will succeed... In this case the default write size is 4096, but the complete JSON string is ~12K chars. This means json.load only gets the first third of the JSON message, so thinks the message is malformed. I think you'll have to collect all of the entries into a buffer until you see a message separator (whatever that may be, '\n' or EOF perhaps?). In the current implementation, directories with more than about 30 files will be un-listable (and presumably uncopyable for the same reasons).

**Comment by sfayer** [comment]
Hmm, looks like this may just need the master branch merging back...

**Comment by sfayer** [comment]
(as I'm testing on the web branch)

**Comment by alexanderrichards** [comment]
yes i believe i have these changes on the master branch already

**Comment by sfayer** [comment]
Yep, testing on master shows that this is already fixed...
