### ISSUE TITLE
CADir initialisation not working

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#285]
The gfal commands can't find the correct cert in the CA dir provided even though it is in the configured system-wide one. This probably means that my function to seed the CA dir from the system one isn't working, or the arguments aren't being passed through correctly.

**Comment by sfayer** [comment]
This is a typo in the default value of this field in the worker (it's missing the word "certificates"...).

**Comment by alexanderrichards** [comment]
which line in worker?

**Comment by sfayer** [comment]
Don't worry about it, I've already fixed it in my general "make voms/grid integration work" branch...

**Comment by alexanderrichards** [comment]
ok thanks
