### ISSUE TITLE
PDM web sign-up e-mail filter is too restrictive

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#325]
user.name+folder@example.com should be accepted, but it seems + characters are not allowed.

**Comment by alexanderrichards** [comment]
at the moment the regex is:
```regex
^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$
```
I can easily add the `+` character in but is there any other changes you think are needed at the same time?

P.s. do people really have + in their email add :open_mouth:
