### ISSUE TITLE
PDM Web flashed message about logging out shows up too late

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#339]
It pops up when I log back in (preumably due to the login page not picking up the flashed message?)... The flashed message also renders poorly (over the title).

![image](https://user-images.githubusercontent.com/3957716/43599893-e4b0cdb4-9680-11e8-8118-af34c9cf2999.png)

**Comment by alexanderrichards** [comment]
ahh good spot. That is exactly why it renders late. as for the formatting. Thats because the flash was left over from the code I started with and I haven't touched it. It needs to have a type associated with it. I'll get on it
