### ISSUE TITLE
PDM Web placeholder for empty directories?

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#340]
Currently empty directories appear as an empty list... I'm wondering if it's worth adding a some place-holder text to say that the directory is empty, just so the user doesn't think something has gone wrong (in the same style as "This page has been intentionally left blank." :-)

**Comment by alexanderrichards** [comment]
empty directories will have at least two entries `.` and `..`. Are you saying you want a message as well as these? wouldn't this be what they expect from  a POSIX like shell?

**Comment by sfayer** [comment]
Hmm, my empty directory has nothing at all (no . or ..)... I'll check that these are appearing in directories with content in a little while (it may be that they've disappeared everywhere, or perhaps they're missing from grid storage elements but not PDM endpoint nodes?).

**Comment by sfayer** [comment]
Yes, I've checked and some servers don't return . and .., which is why I was getting a completely empty directory: These should be inserted at some level if they're missing, maybe a job for Janusz (so it's consistent across all interfaces)?
