### ISSUE TITLE
PDM Web Selecting files and then pressing backspace triggers delete popup

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#341]
Even if I've selected the path box and am intending to delete characters from that... Perhaps it's possible to bind the delete popup action to the delete key rather than backspace?

**Comment by alexanderrichards** [comment]
I think it is also bound to the delete key. The trick I suspect it to discount the backspace if any text entry field has focus. I had a similar problem when renaming files which I solved in an easier way by deselecting them while the text field had focus.
