### ISSUE TITLE
PDM Web task status page seems to have two sorting icons

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#342]
They kind of overlap each other... I'm guessing one is the default (which should be hidden) and one is a extra theme or something?

![image](https://user-images.githubusercontent.com/3957716/43600349-4c60d16a-9682-11e8-869e-84a896549e57.png)

**Comment by alexanderrichards** [comment]
hmmm your correct one is coming from the bootstrap theme but not sure I see this. I'll investigate
