### ISSUE TITLE
Recursive delete seems to fail

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#349]
The recursive bit seems to be tripping up on the . directories (I'm using the newest version of GFAL2 with patches so . is really a directory). Maybe this will be fixed by the infamous ./.. filter as discussed earlier anyway?

```
[2018-08-03 17:16:20,082] StdOutDispatcher :    DEBUG : Subprocess output for job.element 63.0: INFO:__main__:gfal listing root: gsiftp://myserver:2811/~/gridpp at max depth: -1
ERROR:__main__:Error when analysing gsiftp://myserver:2811/~/gridpp/././././././././.
 an end-of-file was reached globus_xio: An end of file occurred
```

**Comment by alexanderrichards** [comment]
We definitely checked recursive deletion so it must be triggered now that . And .. are directories. Let's see what happens when we add the filter

**Comment by alexanderrichards** [comment]
There was another problem caused by the . and .. filter. The referenced PR fixes that problem and has been tested working for recursive removals. Since we no longer have . and .. This issue can be closed with the merge of the above PR
