### ISSUE TITLE
site login on web interface should not be pre-filled in with pdm login details

### ISSUE THREAD

**Issue by marianne013** [ic-hep/pdm#385]
Even if I asked my browser to remember my central login.

![image](https://user-images.githubusercontent.com/7568639/45821641-95b30100-bce1-11e8-8a73-13538ad193fc.png)

**Comment by alexanderrichards** [comment]
@sfayer explicitly asked for this **to** be the case. Why would you not want it pre-filled?

**Comment by alexanderrichards** [comment]
ah I see it is pre-filling with the PDM login not site login

**Comment by alexanderrichards** [comment]
I though this was fixed, I'll investigate
