### ISSUE TITLE
def_path ignored

### ISSUE THREAD

**Issue by duncanrand** [ic-hep/pdm#407]
When I login to  UKI-LT2-IC-HEP ~ is set correctly to /pnfs/hep.ph.ic.ac.uk/data, note

def_path  = /pnfs/hep.ph.ic.ac.uk/data

However when I login to UKI-LT2-Brunel ~ is set to be right at the top of /dpm/brunel.ac.uk/home, despite the fact that

def_path = /dpm/brunel.ac.uk/home

**Comment by duncanrand** [comment]
You can see the Brunel directory tree here

https://dc2-grid-64.brunel.ac.uk/dpm/brunel.ac.uk/home/gridpp/

**Comment by sfayer** [comment]
The starting path when selecting an endpoint on the web interface should default to the def_path field, at the moment it seems to default to just "~".
