### ISSUE TITLE
workerlogs parameter doesn't quite work

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#64]
If set in the config, the framework fails to start with:
ValueError: Unused config params: 'workerlogs'

My guess would be that this needs to be read in an \@startup function and removed from the dict (see the demo service) so that the framework knows it's being used.

**Comment by alexanderrichards** [comment]
yes I commented to this effect in some other PR. looks like it's expecting the config parameter poped from the list in startup. I'll change this.
