### ISSUE TITLE
Branch tidy-up

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#67]
We seem to have quite a few branches open at the moment... It would be good to get everything passing the tests and merged (or deleted, in the case of some branches). I think we have most of the base parts in now, so working with smaller "single feature" now would make things easier to track (and faster to merge).

**Comment by alexanderrichards** [comment]
@sfayer agreed, Just delete my orphaned branch.

**Comment by sfayer** [comment]
Done, all branches have now been tidied up and we're once again back with only master.
