### ISSUE TITLE
pdmcli site name/path format

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#86]
I think the format for URLs on the CLI should be "SiteName:/path/", there shouldn't be any need to specify a full protocol. You can split the URL on the first ':' (maybe write a helper function for doing this?).

**Comment by sfayer** [comment]
The protocol should just default to GRIDFTP because at the moment there is no way of passing a valid protocol through from the command line.

**Comment by martynia** [comment]
urlparse works as advertised:

>>> url = 'localhost:/path/to/file'
>>> urlparse(url)
ParseResult(scheme='localhost', netloc='', path='/path/to/file', params='', query='', fragment=‘')

just take the scheme and the path

J.

**Comment by sfayer** [comment]
Yes, amazingly urlparse does handle that malformed url correctly... It still needs switching to a split so we don't rely on undefined behaviour, however doing that means the request does return 200. Now on to the next bit of testing...

**Comment by sfayer** [comment]
Ah, no you're wrong... Note that it puts the sitename in "scheme" not in "netloc", so that's no good, it just fails silent (aka bug #85).
