### ISSUE TITLE
Does anything actually use src/pdm/workqueue/sql/models/*?

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#93]
Hi Alex,

pylint is getting rather upset about db.Column and many other things in these classes:
https://travis-ci.org/ic-hep/pdm/builds/355493779#L647

But I can't see where there are actually used, perhaps these are old classes which could be removed?

Regards,
Simon

**Comment by sfayer** [comment]
Ah, I think I see it now... @martynia  old branch has dragged in a load of obsolete code with it, hence the sudden drop in pylint score out of nowhere. Grmph.

**Comment by martynia** [comment]
Is that because I merged Alex's branch across, (last week) not from the master ?
And did the final sync with the master leave the obsolete code in??
Janusz Martyniak

**Comment by sfayer** [comment]
No, it's because you explicitly merged obsolete code into your branch here:
https://github.com/ic-hep/pdm/commit/0222f112630a3059508286ef157a659433331194
The workqueue branch never got merged with master (it was an early prototype), newworkqueue was the production code. I guess I can probably just revert that commit without any harm.
