### ISSUE TITLE
Enable broad-excepts by default in pylint

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#95]
Hi @alexanderrichards,

I'm thinking of enabling broad-excepts by default in the pylint policy as I don't think they're too much of a problem and we use them a fair amount... What do you think? Can you think of any reason not to do this?

Regards,
Simon

**Comment by alexanderrichards** [comment]
no generally, in a project like this, especially where we are specifically trying to make things bulletproof and able to keep going in the face of potentially stupid users it makes sense, Of course it just means that we might as a direct result make our own debugging harder but I think that it makes sense for this project.
